[package]
name = "nekor-aal-feature"
version.workspace = true
edition.workspace = true

[features]

[dependencies]
nekor-bitwise = { workspace = true }
nekor-domain = { workspace = true }
nekor-primitive = { workspace = true }
nekor-aal-arch = { workspace = true }

tokel = { workspace = true }

[lints]
workspace = true
