[package]
name = "nekor-boot"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
# Whether the boot protocol library should assume a kernel is being booted.
kernel = []

[dependencies]
nekor-bitwise = { workspace = true }
