[build]
default = "x86_64"

[[platform]]
name = "x86_64"
path = "platform/x86_64/base"
description = "baseline target for all x86_64 processors"

[[platform]]
name = "x86_64/usermode"
path = "platform/x86_64/usermode"
base = "x86_64"
description = "usermode platform for baseline x86_64"
