unstable_features = true
tab_spaces = 4
max_width = 100
reorder_imports = true

wrap_comments = true
comment_width = 80
normalize_comments = false

format_strings = true
format_macro_matchers = false
format_macro_bodies = true
