[package]
name = "nekor-aal-interrupt"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true


[features]

[dependencies]
nekor-aal-agnostic = { workspace = true }
nekor-aal-arch = { workspace = true }
nekor-bitwise = { workspace = true }
zerocopy = { workspace = true }

[lints]
workspace = true
