//! A module exposing well-defined kernel limits in term of the processor.
//!
//! # Core Count
//!
//! The kernel can be configured at compile-time to

use core::num::NonZero;

/// A macro to define various `cfg`-dependant maximum core count settings.
///
/// This uses the feature `"maximum-core-count-{N}"`, where `log2(N) ∈ ℤ` to
/// represent each preset maximum core count that the kernel can drive at most.
///
/// In case of multiple features being enabled at once, the highest core count
/// takes precedence.
///
/// This is implemented for core counts up to `8192` (`2 ^ 13`), which is
/// overkill for most if not all applications.
///
/// The associated `Cargo.toml` feature code can be generated by the following
/// one-liner:
///
/// ```bash
/// echo -ne <tts> | tr "," '\n' | xargs -I{} printf "maximum-core-count-%i = []\n" {}
/// ```
///
/// Where `<tts>` is the input token stream to [`size`].
macro_rules! size {
    () => {};
    ($(($target_size:literal, $feature:literal)),+ $(,)?) => {
        const {
            $(
                if cfg!(feature = $feature) {
                    $target_size
                } else
            )+
            {
                panic!(concat!(
                    "No selected maximal processor core count, please enable one of the following:",
                    $(" maximum-core-count-", $feature),+
                ))
            }
        }
    };
}

/// An uninhabited type that serves as an umbrella type to denote the maximum
/// processor cores that the kernel can manage simultaneously.
pub enum Cores {}

impl Cores {
    /// Determine the maximum number of distinct processor cores that the kernel
    /// can drive simultaneously.
    #[inline]
    #[must_use]
    pub const fn maximum() -> NonZero<usize> {
        const {
            NonZero::new(size!(
                (8192, "maximum-core-count-8192"),
                (4096, "maximum-core-count-4096"),
                (2048, "maximum-core-count-2048"),
                (1024, "maximum-core-count-1024"),
                (512, "maximum-core-count-512"),
                (256, "maximum-core-count-256"),
                (128, "maximum-core-count-128"),
                (64, "maximum-core-count-64"),
                (32, "maximum-core-count-32"),
                (16, "maximum-core-count-16"),
                (8, "maximum-core-count-8"),
                (4, "maximum-core-count-4"),
                (2, "maximum-core-count-2"),
                (1, "maximum-core-count-1"),
            ))
            .expect("bad core count")
        }
    }
}
