//! A module exposing well-defined kernel limits in term of the processor.
//!
//! # Core Count
//!
//! The kernel can be configured at compile-time to

use core::num::NonZero;

/// A macro to define various `cfg`-dependant maximum core count settings.
///
/// This uses the feature `"maximum-core-count-{N}"`, where `log2(N) ∈ ℤ` to
/// represent each preset maximum core count that the kernel can drive at most.
///
/// In case of multiple features being enabled at once, the highest core count
/// takes precedence.
///
/// This is implemented for core counts up to `8192` (`2 ^ 13`), which is
/// overkill for most if not all applications.
///
/// The associated `Cargo.toml` feature code can be generated by the following
/// one-liner:
///
/// ```bash
/// echo -ne <tts> | tr "," '\n' | xargs -I{} printf "maximum-core-count-%i = []\n" {}
/// ```
///
/// Where `<tts>` is the input token stream to [`size`].
macro_rules! size {
    () => {};
    (
        $($target_size:literal),+
    ) => {
        tokel::stream!(
            const {
                #[allow(unreachable_code, reason = "a smaller core count can be shadowed and made unreachable by a greater count")]
                'a: {
                    [<
                        $(
                            {
                                #[cfg(feature = [<
                                     "maximum-core-count-"
                                     // NOTE: This macro parameter can be embedded within a None-delimited token
                                     // group, so we forcibly flatten whatever the macro expansion engine gives us.
                                     [< $target_size >]:flatten
                                >]:to_string:concatenate)]
                                break 'a $target_size;
                            }
                        )*
                    // NOTE: The `reverse` here is `TokenGroup`-based, so it won't reorder the labelled break expression internally.
                    >]:reverse

                    {
                        unreachable!(
                            [<
                                "No selected maximal processor core count, please enable one of the following:"
                                $(
                                    " "

                                    "`" [< "maximum-core-count-" [< $target_size >]:flatten >]:to_string:concatenate "`"
                                )*
                            >]:to_string:concatenate
                        )
                    }
                }
            }
        )
    };
}

/// An uninhabited type that serves as an umbrella type to denote the maximum
/// processor cores that the kernel can manage simultaneously.
pub enum Cores {}

impl Cores {
    /// Determine the maximum number of distinct processor cores that the kernel
    /// can drive simultaneously.
    #[inline]
    #[must_use]
    pub const fn maximum() -> NonZero<usize> {
        const {
            NonZero::new(size!(
                1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192
            ))
            .expect("bad core count")
        }
    }
}
