[package]
name = "nekor-aal-arch"
version = "0.1.0"
edition.workspace = true

[features]

[dependencies]
nekor-aal-agnostic = { version = "*", path = "../agnostic" }
nekor-bitwise = { version = "*", path = "../../nekor-bitwise" }
nekor-primitive = { version = "*", path = "../../nekor-primitive" }

[lints]
workspace = true
