[package]
name = "nekor-register"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
nekor-primitive = { workspace = true }

[lints]
workspace = true
