[package]
name = "nekor-build"
version.workspace = true
edition.workspace = true

[dependencies]
cargo_metadata = "0.23.1"
clap = { version = "4.6.0", features = ["derive", "cargo"] }
fack.workspace = true
nekor-build-kdl-config.workspace = true
minijinja = { version = "2.21.0", features = ["loader"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "1.1.0"
walkdir.workspace = true

[lints]
workspace = true
