[package]
name = "nekor-bitwise-extract-macro"
version = "0.0.0"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
nekor-bitwise-extract-macro-impl = { workspace = true }
proc-macro2 = "1.0.103"
syn = "2.0.108"
