[package]
name = "nekor-aal-isolate"
version.workspace = true
edition.workspace = true


[features]
default = ["arch-x86_64"]

arch-x86_64 = ["arch-x86_64-xsave-4096"]
arch-x86_64-xsave-512 = []
arch-x86_64-xsave-1024 = []
arch-x86_64-xsave-2048 = []
arch-x86_64-xsave-4096 = []
arch-x86_64-xsave-8192 = []
arch-x86_64-xsave-16384 = []

[dependencies]
nekor-domain = { workspace = true }
nekor-bitwise = { workspace = true }
nekor-aal-arch = { workspace = true }
nekor-aal-hotpatch = { workspace = true }
nekor-aal-agnostic = { workspace = true }
nekor-aal-feature = { workspace = true }

tokel = { workspace = true }


[lints]
workspace = true
