[package]
name = "nekor-backoff"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
usermode = []

[dependencies]

[lints]
workspace = true
