[package]
name = "nekor-cpu"
version.workspace = true
edition.workspace = true

[features]
default = ["maximum-core-count-16"]

maximum-core-count-1 = []
maximum-core-count-2 = []
maximum-core-count-4 = []
maximum-core-count-8 = []
maximum-core-count-16 = []
maximum-core-count-32 = []
maximum-core-count-64 = []
maximum-core-count-128 = []
maximum-core-count-256 = []
maximum-core-count-512 = []
maximum-core-count-1024 = []
maximum-core-count-2048 = []
maximum-core-count-4096 = []
maximum-core-count-8192 = []

[dependencies]
nekor-aal = { workspace = true }
nekor-domain = { workspace = true }
nekor-structure = { workspace = true }

tokel = { workspace = true }

[lints]
workspace = true
