//! Type-level wrappers for low-level architectural entry.

use core::marker;

/// A marker trait that describes low-level contextual entry.
///
/// # Safety
///
/// This must be implemented by either the [`LowLevel`] type or a wrapper over
/// [`LowLevel`].
///
/// See the [`LowLevel`] documentation for further information regarding
/// wrappers.
pub unsafe trait Contextual {}

/// A transparent wrapper acting as a type-level proof of a low-level
/// architectural entry.
///
/// `LowLevel<T>` serves as a strict boundary between standard Rust execution
/// and hardware-level transitions (e.g., Interrupt Service Routines, Syscalls,
/// or Context Switches). It ensures that privileged functions can only be
/// executed when the CPU is in a verified, hardware-managed state.
///
/// # Guaranteeing Low-Level Context
///
/// This type achieves a strict safety guarantee across the entire codebase
/// through a combination of Rust's privacy system and Application Binary
/// Interface (ABI) guarantees:
///
/// 1. **Unforgeability:** The internal data is completely private. Because
///    there is no public constructor, it is mathematically impossible for safe
///    Rust code to construct a `LowLevel<T>`.
/// 2. **Hardware Transparency:** Because it is marked `#[repr(transparent)]`,
///    the struct is binary-compatible with `T`.
///
/// This combination creates an "Assembly Loophole." When a naked assembly
/// stub executes a transition (e.g., reading an error code into `%rdi` and
/// issuing a `call`), the hardware moves the raw bits, and the Rust compiler
/// interprets that register directly as `LowLevel<T>`.
///
/// Therefore, if an internal function requires `LowLevel<T>` as an input,
/// the compiler guarantees the caller is either a trusted, `unsafe`
/// constructor within the privileged module, or a direct hardware transition.
///
/// # Isolating Contexts via Wrapper Types
///
/// While `LowLevel<T>` guarantees that data originated from *some* hardware
/// entry point, not all architectural entries are equal. For example, an
/// Interrupt handler and a Context Switch routine are both "low-level", but
/// they have entirely different invariants regarding stack layout, segment
/// registers, and CPU flags.
///
/// To prevent cross-contamination (e.g., passing an exception token to a
/// syscall handler), `LowLevel<T>` should rarely be used directly in function
/// signatures. Instead, it must be encapsulated in **Context-Specific
/// Wrappers**.
///
/// By defining a newtype wrapper around `LowLevel<T>`, you create an
/// unforgeable token tied to a specific execution domain:
///
/// ```
/// use core::marker::PhantomData;
/// # struct LowLevel<T>(pub T, PhantomData<*mut ()>);
///
/// /// A token proving execution within a Non-Maskable Interrupt (NMI).
/// #[repr(transparent)]
/// pub struct NmiContext<T>(
///     pub LowLevel<T>,
///     // NOTE(invariant): This is to remain private to avoid a public constructor.
///     PhantomData<Self>
/// );
/// ```
///
/// In this pattern, the constructor for `NmiContext` is kept strictly internal
/// (private). This ensures that a function demanding an
/// `NmiContext<T>` can *never* accidentally be fed a token generated by a
/// standard interrupt handler, completely eliminating Type Confusion at the
/// hardware boundary.
///
/// # Variance and Thread Safety
///
/// This type utilizes `core::marker::PhantomData<*mut ()>` to enforce correct
/// compiler behavior:
///
/// * **Covariance:** The type is covariant over `T`. If `T` contains a lifetime
///   (e.g., `&'a State`), standard lifetime subtyping applies, preventing
///   unnecessary compiler friction.
/// * **Thread Isolation:** The `*mut ()` marker ensures the type is `!Send` and
///   `!Sync`. A low-level token is inextricably bound to the specific hardware
///   execution thread that birthed it. It cannot be safely sent to another CPU
///   core or user-space thread where the original hardware invariants no longer
///   apply.
#[repr(transparent)]
pub struct LowLevel<T>(
    pub T,
    // NOTE(invariant): This is to remain private to avoid a public constructor.
    // NOTE(variance): Force `LowLevel` to be covariant over `T`.
    marker::PhantomData<*mut ()>,
);

// SAFETY: This is being implemented for `LowLevel`.
unsafe impl<T> Contextual for LowLevel<T> {}
