[package]
name = "nekor-bitwise-extract-128"
version.workspace = true
edition.workspace = true

[dependencies]
nekor-bitwise-extract-128-8 = { workspace = true }
nekor-bitwise-extract-128-16 = { workspace = true }
nekor-bitwise-extract-128-32 = { workspace = true }
nekor-bitwise-extract-128-64 = { workspace = true }
nekor-bitwise-extract-128-128 = { workspace = true }

nekor-bitwise-extract-core = { workspace = true }
