[package]
name = "nekor-platform"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

build = "build.rs"

[dependencies]

[lints]
workspace = true
