[package]
name = "nekor-aal-agnostic"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true


[features]

[dependencies]
zerocopy.workspace = true

nekor-bitwise = { workspace = true }
nekor-primitive = { workspace = true }

[lints]
workspace = true
