[package]
name = "nekor-aal"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]

[dependencies.nekor-aal-arch]
workspace = true

[dependencies.nekor-aal-cache]
workspace = true

[dependencies.nekor-aal-critical]
workspace = true

[dependencies.nekor-aal-feature]
workspace = true

[dependencies.nekor-aal-hotpatch]
workspace = true

[dependencies.nekor-aal-local]
workspace = true

[dependencies.nekor-aal-signal]
workspace = true

[lints]
workspace = true
