[package]
name = "nekor-sync"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]

[dependencies]
nekor-aal-signal = { workspace = true }
nekor-aal-cache = { workspace = true }
nekor-primitive = { workspace = true }
nekor-bitwise = { workspace = true }
nekor-backoff = { workspace = true }

[lints]
workspace = true
