[package]
name = "nekor-aal-local"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]

[dependencies]

[dependencies.nekor-aal-arch]
workspace = true

[lints]
workspace = true
