[package]
name = "nekor-aal-signal"
version.workspace = true
edition.workspace = true

[features]

[dependencies]

[dependencies.nekor-aal-arch]
workspace = true

[dependencies.nekor-aal-cache]
workspace = true

[dependencies.nekor-aal-feature]
workspace = true

[dependencies.nekor-aal-hotpatch]
workspace = true

[dependencies.nekor-bitwise]
workspace = true

[lints]
workspace = true
